/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author Vinicius
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu8 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        Menucadastrarprodutos = new javax.swing.JMenuItem();
        Menuconsultarprodutos2 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        Menucadastrarclientes = new javax.swing.JMenuItem();
        Menuconsultarclientes = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jMenu14 = new javax.swing.JMenu();
        jMenu15 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu8.setIcon(new javax.swing.ImageIcon("D:\\Projeto Java\\Icones\\Accounting_icon-icons.com_74682.png")); // NOI18N
        jMenu8.setText("Cadastro   |");

        jMenu2.setIcon(new javax.swing.ImageIcon("D:\\Projeto Java\\Icones\\produtos.png")); // NOI18N
        jMenu2.setText("Produtos");

        Menucadastrarprodutos.setIcon(new javax.swing.ImageIcon("D:\\Projeto Java\\Icones\\notepad_notes_22702.png")); // NOI18N
        Menucadastrarprodutos.setText("Cadastrar");
        jMenu2.add(Menucadastrarprodutos);

        Menuconsultarprodutos2.setIcon(new javax.swing.ImageIcon("D:\\Projeto Java\\Icones\\Search_find_magnifier_248.png")); // NOI18N
        Menuconsultarprodutos2.setText("Consultar");
        jMenu2.add(Menuconsultarprodutos2);

        jMenu8.add(jMenu2);

        jMenu1.setIcon(new javax.swing.ImageIcon("D:\\Projeto Java\\Icones\\pessoas.png")); // NOI18N
        jMenu1.setText("Clientes");

        Menucadastrarclientes.setIcon(new javax.swing.ImageIcon("D:\\Projeto Java\\Icones\\notepad_notes_22702.png")); // NOI18N
        Menucadastrarclientes.setText("Cadastrar");
        jMenu1.add(Menucadastrarclientes);

        Menuconsultarclientes.setIcon(new javax.swing.ImageIcon("D:\\Projeto Java\\Icones\\Search_find_magnifier_248.png")); // NOI18N
        Menuconsultarclientes.setText("Consultar");
        jMenu1.add(Menuconsultarclientes);

        jMenu8.add(jMenu1);

        jMenuBar2.add(jMenu8);

        jMenu11.setIcon(new javax.swing.ImageIcon("D:\\Projeto Java\\Icones\\money_dollar_cash_coins_riches_wealth_icon-icons.com_53585.png")); // NOI18N
        jMenu11.setText("Financeiro   |");
        jMenuBar2.add(jMenu11);

        jMenu14.setIcon(new javax.swing.ImageIcon("D:\\Projeto Java\\Icones\\tool_icon-icons.com_71923.png")); // NOI18N
        jMenu14.setText("Ferramentas   |");
        jMenuBar2.add(jMenu14);

        jMenu15.setIcon(new javax.swing.ImageIcon("D:\\Projeto Java\\Icones\\systemshutdown_103390.png")); // NOI18N
        jMenu15.setText("Sair");
        jMenuBar2.add(jMenu15);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 798, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Menucadastrarclientes;
    private javax.swing.JMenuItem Menucadastrarprodutos;
    private javax.swing.JMenuItem Menuconsultarclientes;
    private javax.swing.JMenuItem Menuconsultarprodutos2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar2;
    // End of variables declaration//GEN-END:variables
}
